apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: googleservice
  name: googleservice-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleservice
  strategy: {}
  template:
    metadata:
      labels:
        app: googleservice
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      serviceAccountName: default
      containers:
        - image: thecodingadventure/googleservice:a4bef9afdfa69015e18b39f9b4a60b670c1c0bdc
          name: googleservice-container
          volumeMounts:
          - mountPath: /tmp
            name: vol
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            readOnlyRootFilesystem: false
