apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: googleservice
  name: googleservice-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleservice
  strategy: {}
  template:
    metadata:
      labels:
        app: googleservice
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      serviceAccountName: default
      containers:
        - image: thecodingadventure/googleservice:e9532493d4a94280f84908a5dad4c0dafe25c4d9
          name: googleservice-container
          volumeMounts:
          - mountPath: /tmp
            name: vol
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            readOnlyRootFilesystem: false
