apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: googleservice
  name: googleservice-depl
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: googleservice
  strategy: {}
  template:
    metadata:
      labels:
        app: googleservice
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      serviceAccountName: default
      containers:
        - image: thecodingadventure/googleservice:eb3fb31d67398f7b78a1214af8fcab1505076afa
          name: googleservice-container
          volumeMounts:
          - mountPath: /tmp
            name: vol
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            readOnlyRootFilesystem: false
