apiVersion: v1
kind: Service
metadata:
  labels:
    app: googleservice
  name: googleservice-srv
spec:
  selector:
    app: googleservice
  ports:
    - name: youtubeservice
      protocol: TCP
      port: 3000
      targetPort: 3000